### KNN(K-Nearest Neighbors) Implementation for redwine dataset

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data = pd.read_csv('data/winequality-red.csv')
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [12]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1:].values

In [13]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size =0.25,random_state = 2)

In [14]:
# KNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [15]:
knn_model = KNeighborsClassifier(n_neighbors=3)

print('<--------------------KNN Classifier model------------------>')
knn_model.fit(xtrain,ytrain)
ypred = knn_model.predict(xtest)
ypred

<--------------------KNN Classifier model------------------>


C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([7, 7, 4, 6, 6, 5, 6, 6, 5, 5, 4, 6, 6, 6, 5, 7, 6, 6, 6, 6, 4, 6,
       6, 6, 5, 7, 5, 5, 7, 6, 5, 5, 5, 5, 5, 5, 6, 6, 7, 6, 5, 5, 6, 5,
       5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 7, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
       7, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 7, 6, 7, 5, 5, 6,
       5, 6, 7, 5, 6, 4, 6, 6, 5, 5, 5, 5, 6, 5, 3, 5, 5, 6, 5, 6, 6, 6,
       5, 5, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5, 7, 5, 6, 4, 6, 5, 6, 5,
       5, 6, 7, 5, 6, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6, 5, 7, 6, 5, 5,
       7, 4, 7, 5, 4, 6, 5, 5, 6, 5, 7, 6, 7, 5, 5, 5, 6, 6, 7, 6, 5, 5,
       5, 6, 5, 6, 5, 6, 5, 6, 5, 7, 5, 5, 6, 6, 4, 5, 6, 4, 4, 6, 5, 6,
       6, 7, 6, 5, 5, 5, 5, 5, 6, 7, 5, 6, 7, 4, 5, 6, 5, 7, 6, 5, 6, 5,
       6, 6, 5, 7, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 3, 6, 5, 5, 5, 7,
       5, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 7, 6, 5, 5, 6, 6, 5, 6, 5, 6,
       5, 7, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 6, 3, 6, 5, 5, 7, 5,
       4, 7, 6, 5, 7, 6, 5, 6, 3, 5, 6, 5, 6, 5, 7,

In [16]:
# performance metric

print("Accuracy score :\t",accuracy_score(ytest,ypred))
print()
print('Confusion Martix :\n',confusion_matrix(ytest,ypred))
print()
print('classification Report :\n', classification_report(ytest,ypred))

Accuracy score :	 0.5025

Confusion Martix :
 [[  0   0   0   1   0   0]
 [  1   1   7   4   0   0]
 [  1   6 101  34   6   0]
 [  1   7  81  83  13   0]
 [  1   0  12  19  16   0]
 [  0   0   2   1   2   0]]

classification Report :
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.07      0.08      0.07        13
           5       0.50      0.68      0.58       148
           6       0.58      0.45      0.51       185
           7       0.43      0.33      0.38        48
           8       0.00      0.00      0.00         5

    accuracy                           0.50       400
   macro avg       0.26      0.26      0.26       400
weighted avg       0.51      0.50      0.50       400



C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
# KNN model after scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc_x = sc.fit_transform(x)

In [18]:
sc_x.shape

(1599, 11)

In [19]:
from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(sc_x,y,test_size =0.25,random_state = 2)

In [20]:
knn_model = KNeighborsClassifier(n_neighbors=3)

print('<--------------------KNN Classifier model------------------>')
knn_model.fit(xtrain,ytrain)
ypred = knn_model.predict(xtest)
ypred

<--------------------KNN Classifier model------------------>


C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([6, 5, 5, 6, 6, 6, 4, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 7, 6, 6, 6, 6,
       6, 6, 5, 7, 5, 6, 7, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5,
       5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 5, 7, 5, 6, 6, 4, 5, 6, 5, 6, 6,
       7, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 5, 5, 7, 5, 5, 7, 6, 7, 6,
       5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5, 3, 4, 6, 6, 6, 5, 6, 7,
       6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 7, 6, 5, 5, 5,
       7, 5, 6, 6, 6, 5, 5, 7, 6, 5, 6, 6, 5, 5, 4, 5, 6, 4, 6, 6, 6, 6,
       6, 6, 7, 5, 6, 6, 5, 5, 6, 5, 6, 6, 7, 6, 3, 5, 6, 6, 7, 6, 6, 6,
       6, 6, 5, 6, 5, 6, 5, 6, 5, 4, 5, 5, 6, 6, 6, 7, 5, 5, 5, 5, 5, 5,
       5, 7, 5, 5, 5, 5, 5, 5, 6, 7, 6, 5, 7, 5, 5, 5, 7, 5, 6, 5, 5, 6,
       5, 6, 4, 6, 6, 5, 6, 6, 6, 6, 5, 4, 5, 5, 6, 5, 6, 6, 5, 5, 7, 6,
       6, 6, 5, 6, 6, 6, 5, 7, 6, 5, 6, 5, 7, 5, 5, 4, 6, 6, 6, 5, 5, 5,
       6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 6, 7, 5,
       5, 5, 7, 6, 7, 7, 5, 5, 3, 5, 6, 6, 4, 6, 7,

In [21]:
# performance metric after scaling

print("Accuracy score :\t",accuracy_score(ytest,ypred))
print()
print('Confusion Martix :\n',confusion_matrix(ytest,ypred))
print()
print('classification Report :\n', classification_report(ytest,ypred))

Accuracy score :	 0.5425

Confusion Martix :
 [[  0   0   0   1   0   0]
 [  2   1   7   3   0   0]
 [  2   6  91  45   4   0]
 [  0   5  58 106  16   0]
 [  1   0  10  18  19   0]
 [  0   0   0   3   2   0]]



C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


classification Report :
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.08      0.08      0.08        13
           5       0.55      0.61      0.58       148
           6       0.60      0.57      0.59       185
           7       0.46      0.40      0.43        48
           8       0.00      0.00      0.00         5

    accuracy                           0.54       400
   macro avg       0.28      0.28      0.28       400
weighted avg       0.54      0.54      0.54       400



C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
# Different K

knn_model = KNeighborsClassifier(n_neighbors=126)

print('<--------------------KNN Classifier model------------------>')
knn_model.fit(xtrain,ytrain)
ypred = knn_model.predict(xtest)

print("Accuracy score :\t",accuracy_score(ytest,ypred))
print()
print('Confusion Martix :\n',confusion_matrix(ytest,ypred))
print()
print('classification Report :\n', classification_report(ytest,ypred))

<--------------------KNN Classifier model------------------>

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)



Accuracy score :	 0.55

Confusion Martix :
 [[  0   0   1   0   0   0]
 [  0   0  10   3   0   0]
 [  0   0 113  35   0   0]
 [  0   0  79 106   0   0]
 [  0   0   6  41   1   0]
 [  0   0   0   4   1   0]]

classification Report :
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00        13
           5       0.54      0.76      0.63       148
           6       0.56      0.57      0.57       185
           7       0.50      0.02      0.04        48
           8       0.00      0.00      0.00         5

    accuracy                           0.55       400
   macro avg       0.27      0.23      0.21       400
weighted avg       0.52      0.55      0.50       400



C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
### After scaling independent variable-x, the accuracy of knn model improves slightly
# IN k = 26, WE get optimum better performance