In [113]:
import numpy as np
import pandas as pd

In [114]:
data = pd.read_csv('dataset/diabetes_na.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0      148             72           35.0        0  33.6   
1          NaN       85             66           29.0        0  26.6   
2          8.0      183             64            0.0        0   NaN   
3          1.0       89             66           23.0       94  28.1   
4          0.0      137             40           35.0      168  43.1   

   DiabetesPedigreeFunction   Age  Outcome  
0                     0.627  50.0        1  
1                     0.351   NaN        0  
2                     0.672  32.0        1  
3                     0.167  21.0        0  
4                     2.288  33.0        1

In [115]:
data.isna().sum()

Pregnancies                 2
Glucose                     0
BloodPressure               0
SkinThickness               1
Insulin                     0
BMI                         1
DiabetesPedigreeFunction    0
Age                         1
Outcome                     0
dtype: int64

In [116]:
# use fillna if features haa any null value
data=data.fillna(method='bfill')
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [124]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1:].values

y = np.array(y).ravel()

In [132]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=2)
print('****************Training Data Shape********************\n')
print('Training data-X- Shape:\t',xtrain.shape)
print()
print('Training data-y- Shape:\t',ytrain.shape)
print()
print('****************Testing Data Shape********************\n')
print('Testing data(x-Input) Shape:\t',xtest.shape)
print()
print('Testing data(y-Outcome) Shape:\t',ytest.shape)

****************Training Data Shape********************

Training data-X- Shape:	 (576, 8)

Training data-y- Shape:	 (576,)

****************Testing Data Shape********************

Testing data(x-Input) Shape:	 (192, 8)

Testing data(y-Outcome) Shape:	 (192,)


In [126]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


log_reg=LogisticRegression(solver='liblinear',verbose=2)
#Train the model
print('Training the model..............\n')
log_reg.fit(lda_train,ytrain)
#Test the model
ypred=log_reg.predict(lda_test)
print('Predicted Label for the input samples:\n',ypred)
print()
print('Testing is completed................\n')
print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))


Training the model..............

[LibLinear]Predicted Label for the input samples:
 [0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1
 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0]

Testing is completed................

Testing samples are: 	 192

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.765625

Confusion Matrix:
 [[120  14]
 [ 31  27]]

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84       134
           1       0.66      0.47      0.55        58

    accuracy                           0.77       192
   macro avg       0.73      0.68      0.69       192
weighted av

# Linear Discriminant Analysis (LDA)

In [68]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import mean_squared_error, r2_score

# Create and fit your regression model using the LDA-transformed features
lda = LinearDiscriminantAnalysis()
X= lda.fit_transform(x,y)

xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=.25,random_state=2)

log_reg=LogisticRegression(solver='liblinear',verbose=2)


log_reg.fit(xtrain,ytrain)

ypred=log_reg.predict(xtest)


print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))


[LibLinear]Testing samples are: 	 192

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.7760416666666666

Confusion Matrix:
 [[121  13]
 [ 30  28]]

Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.90      0.85       134
           1       0.68      0.48      0.57        58

    accuracy                           0.78       192
   macro avg       0.74      0.69      0.71       192
weighted avg       0.77      0.78      0.76       192



In [78]:
# Principal Component Analysis (PCA)
from sklearn.decomposition import PCA

pca = PCA(n_components=2)  # Specify the number of components you want to keep
X = pca.fit_transform(x,y)

xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=.25,random_state=2)

log_reg=LogisticRegression(solver='liblinear',verbose=2)

log_reg.fit(xtrain,ytrain)

ypred=log_reg.predict(xtest)

print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))

[LibLinear]Testing samples are: 	 192

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.75

Confusion Matrix:
 [[118  16]
 [ 32  26]]

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.88      0.83       134
           1       0.62      0.45      0.52        58

    accuracy                           0.75       192
   macro avg       0.70      0.66      0.68       192
weighted avg       0.74      0.75      0.74       192



In [86]:
# GridSearchCV for hyperparameter tuning

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

ran_reg = RandomForestRegressor()  # Create an instance of the RandomForestRegressor

param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [3, 5, 7]
}

grid_search = GridSearchCV(ran_reg, param_grid, cv=5)
grid_search.fit(x,y)

best_model = grid_search.best_estimator_
best_model



RandomForestRegressor(max_depth=5)

In [87]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.25,random_state=2)

log_reg=LogisticRegression(solver='liblinear',verbose=2)

log_reg.fit(xtrain,ytrain)

ypred=log_reg.predict(xtest)

print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))

[LibLinear]Testing samples are: 	 192

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.7604166666666666

Confusion Matrix:
 [[121  13]
 [ 33  25]]

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84       134
           1       0.66      0.43      0.52        58

    accuracy                           0.76       192
   macro avg       0.72      0.67      0.68       192
weighted avg       0.75      0.76      0.74       192



In [90]:
# RandomizedSearchCV for hyperparameter tuning
param_dist = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 7],
    # Add other hyperparameters as needed
}
random_search = RandomizedSearchCV(RandomForestRegressor(), param_dist, n_iter=10, cv=5)
random_search.fit(x,y)
best_model_random = random_search.best_estimator_

best_model_random

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:307: UserWarning: The total space of parameters 9 is smaller than n_iter=10. Running 9 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


RandomForestRegressor(max_depth=5)

In [92]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.25,random_state=2)

log_reg=LogisticRegression(solver='liblinear',verbose=2)

log_reg.fit(xtrain,ytrain)

ypred=log_reg.predict(xtest)

print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))

[LibLinear]Testing samples are: 	 192

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.7604166666666666

Confusion Matrix:
 [[121  13]
 [ 33  25]]

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84       134
           1       0.66      0.43      0.52        58

    accuracy                           0.76       192
   macro avg       0.72      0.67      0.68       192
weighted avg       0.75      0.76      0.74       192



In [93]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler 

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

xtrain,xtest,ytrain,ytest=train_test_split(X_scaled,y,test_size=.25,random_state=2)

log_reg=LogisticRegression(solver='liblinear',verbose=2)

log_reg.fit(xtrain,ytrain)

ypred=log_reg.predict(xtest)

print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))

[LibLinear]Testing samples are: 	 192

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.7604166666666666

Confusion Matrix:
 [[120  14]
 [ 32  26]]

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.90      0.84       134
           1       0.65      0.45      0.53        58

    accuracy                           0.76       192
   macro avg       0.72      0.67      0.68       192
weighted avg       0.75      0.76      0.75       192



# Handling imbalance dataset

In [97]:
from sklearn.utils import resample

df_majority=data[data.Outcome==0]
df_minority=data[data.Outcome==1]

df_minority_upsampled=resample(df_minority,
                                replace=True, # sample with replacement
                                n_samples=500, #to match the majority class
                                random_state=12
                                )
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [98]:
df_upsampled.shape

(1000, 9)

In [99]:
x=df_upsampled.iloc[:,:-1]
y=df_upsampled.iloc[:,-1:]

In [100]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.25,random_state=2)

log_reg=LogisticRegression(solver='liblinear',verbose=2)

log_reg.fit(xtrain,ytrain)

ypred=log_reg.predict(xtest)

print('Testing samples are: \t',len(ypred))
print()
print('<--------------Performance Measures for Logistic Regression------------------>\n') 
print('Accuracy Score:\t',accuracy_score(ytest,ypred))
print()

print('Confusion Matrix:\n',confusion_matrix(ytest,ypred))
print()

print('Classification Report:\n',classification_report(ytest,ypred))

[LibLinear]Testing samples are: 	 250

<--------------Performance Measures for Logistic Regression------------------>

Accuracy Score:	 0.736

Confusion Matrix:
 [[87 34]
 [32 97]]

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.72      0.72       121
           1       0.74      0.75      0.75       129

    accuracy                           0.74       250
   macro avg       0.74      0.74      0.74       250
weighted avg       0.74      0.74      0.74       250



C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# cross validation

In [107]:
from sklearn.model_selection import cross_val_score

# Perform cross validation
cv_scores = cross_val_score(log_reg, x, y, cv=5)
0
# Calculate the mean cross validation score
mean_cv_score = np.mean(cv_scores)
print()
print("\n Cross Validation score",mean_cv_score)

[LibLinear][LibLinear][LibLinear][LibLinear][LibLinear]

 Cross Validation score 0.770876835582718


# K-Fold Cross validation

In [127]:
model = log_reg
kf = KFold(n_splits=5, shuffle=True)

# Perform K-fold cross validation
cv_scores = []
for train_index, test_index in kf.split(x):
    # Train the model on the training fold
    model.fit(x[train_index], y[train_index])

    # Evaluate the model on the test fold
    y_pred = model.predict(x[test_index])
    cv_scores.append(np.mean((y[test_index] - y_pred)**2))

# Calculate the mean cross validation score
mean_cv_score = np.mean(cv_scores)

print()
print("\n K Fold Cross Validation score",mean_cv_score)

[LibLinear][LibLinear][LibLinear][LibLinear][LibLinear]

 K Fold Cross Validation score 0.23697478991596638


# LOOCV

In [134]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import LeaveOneOut
# Create a logistic regression model
log_reg = LogisticRegression(max_iter=1000)

# Leave-One-Out Cross-Validation (LOOCV)
loo = LeaveOneOut()
loo_cv_scores = cross_val_score(log_reg, xtrain, ytrain, cv=loo, scoring='neg_mean_squared_error')
loo_cv_rmse_scores = np.sqrt(-loo_cv_scores)
loo_cv_r2_scores = cross_val_score(log_reg, xtrain, ytrain, cv=loo, scoring='r2')


C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)
C:\Users\2001s\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn

# 

# 

## Model Comparison

 LogisticRegression  model with LDA techniques has high accuracy compare all other technique..