# NUMPY Practice assignment mini case study

In [1]:
import numpy as np

np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])


In [2]:
np_olympic_country

array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'], dtype='<U5')

### 1. Index of maximum gold country

In [7]:
max_country_gold = np_olympic_country_gold.argmax()
print('Index of maximum gold country : ',max_country_gold)

Index of maximum gold country :  3


### 2. Country With maximum gold

In [8]:
print(' Country With maximum gold is :', np_olympic_country[max_country_gold])

 Country With maximum gold is : US


### 3. Country with gold more than 20 Medals

In [11]:
n = len(np_olympic_country_gold)
print('Country with gold more than 20 Medals..\n')
for i in range(0,n):
    if np_olympic_country_gold[i] > 20:
        print(np_olympic_country[i])
        

Country with gold more than 20 Medals..

GBR
China
RUS
US


### 4. Evaluate Dataset and print medals

In [13]:
# 1.Country with gold Medals
n = len(np_olympic_country_gold)
print('Country with gold Medals..\n')
for i in range(0,n):
    print(f'{np_olympic_country[i]} : {np_olympic_country_gold[i]}')

Country with gold Medals..

GBR : 29
China : 38
RUS : 24
US : 46
KOR : 13
JPN : 7
GER : 11


In [21]:
#2. total Medals of each country
n = len(np_olympic_country_gold)
print('Country with Total Medals..\n')
total_medals =()
for i in range(0,n):
    total_medals = np_olympic_country_bronze[i] + np_olympic_country_gold[i]+np_olympic_country_silver[i]
    print(f'{np_olympic_country[i]}   : {total_medals}')

Country with Total Medals..

GBR   : 65
China   : 88
RUS   : 81
US   : 103
KOR   : 28
JPN   : 38
GER   : 36


# Numpy Practice Assignments

### 1. 3 X 3 X 3 array matrix using random values

In [29]:
ran_val = np.random.random((3,3,3))

In [30]:
print(ran_val)

[[[0.38772794 0.80214186 0.51464898]
  [0.71780847 0.93576473 0.46475414]
  [0.9084361  0.37546986 0.01752809]]

 [[0.93686563 0.67510835 0.69936653]
  [0.41300084 0.25770247 0.2150205 ]
  [0.41030351 0.23096799 0.05952148]]

 [[0.94429416 0.67076369 0.37084775]
  [0.24644638 0.54675841 0.30284696]
  [0.97816598 0.85364414 0.57567883]]]


### 2. 5 X 5 matrix with 1 2 3 4 values below diagonals

In [32]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
for i in range(1,len(d)):
    for j in range(0,i):
        d[i][j] = j+1

In [39]:
d


array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [1., 2., 3., 1., 0.],
       [1., 2., 3., 4., 1.]])

### 3. 8X8 matrix with checkboard pattern

In [44]:
checkerboard = np.zeros((8, 8), dtype=int)


checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 4. Normalize the 5x5 matrix using random

In [46]:
# Create a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Find the minimum and maximum values in the matrix
min_value = random_matrix.min()
max_value = random_matrix.max()

# Normalize the matrix to range [0, 1]
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("Original Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.27079529 0.36996627 0.58743581 0.35328403 0.00140357]
 [0.02823023 0.8240139  0.50859168 0.23048022 0.91375174]
 [0.44185842 0.44580931 0.85362438 0.62020952 0.72323758]
 [0.10660695 0.90642345 0.64903037 0.64015627 0.32024658]
 [0.81580153 0.50891772 0.21317691 0.51722119 0.57616378]]

Normalized Matrix:
[[0.29527293 0.40397155 0.64233399 0.3856866  0.        ]
 [0.02940397 0.9016408  0.55591509 0.25108468 1.        ]
 [0.48277057 0.48710103 0.93409604 0.67825636 0.79118262]
 [0.11531055 0.99196766 0.7098461  0.70011945 0.34947514]
 [0.89263944 0.55627244 0.23211899 0.56537365 0.62997902]]


### 5. find common values between two arrays

In [48]:
array1 = np.array([12, 2, 3, 4, 15])
array2 = np.array([33, 4, 15, 6, 7])

common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)


Common values: [ 4 15]


### 6. get the dates of yesterday, today, and tomorrow

In [50]:
from datetime import datetime, timedelta
today = datetime.now()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday.strftime('%Y-%m-%d'))
print("Today:", today.strftime('%Y-%m-%d'))
print("Tomorrow:", tomorrow.strftime('%Y-%m-%d'))


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


### 7. Consider two random arrays A and B, check if they are equal

In [61]:
A = np.random.rand(5)
B = np.random.rand(5)
print(f'value of Array A :{A}  \n')
print(f'Value of Array B : {B} \n')
are_equal = np.array_equal(A, B)

if are_equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


value of Array A :[0.5415344  0.60971082 0.25525986 0.48505614 0.7698278 ]  

Value of Array B : [0.64517698 0.07615852 0.21985817 0.40970614 0.08551208] 

Arrays A and B are not equal.


### 8. Create random vector of size 10 and replace the maximum value by 0

In [57]:
random_vector = np.random.random(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)
print("Random vector: \n", random_vector)
print()
print("Random vector with the maximum value: \n", random_vector[max_index])
random_vector[max_index] = 0
print()
print("Random vector with the maximum value replaced with 0 : \n", random_vector)


Random vector: 
 [0.83976428 0.58785742 0.29192122 0.40766973 0.52883836 0.04804868
 0.76926908 0.14643853 0.56822364 0.21794787]

Random vector with the maximum value: 
 0.8397642796512598

Random vector with the maximum value replaced with 0 : 
 [0.         0.58785742 0.29192122 0.40766973 0.52883836 0.04804868
 0.76926908 0.14643853 0.56822364 0.21794787]


### 9. print all the values of an array

In [62]:
my_array = np.array([190,3,2,13,45,367,89])

print(my_array)

[190   3   2  13  45 367  89]


### 10. Subtract the mean of each row of a matrix

In [65]:
random_matrix = np.random.rand(3, 4)

row_means = np.mean(random_matrix, axis=1)
print('Mean of each rows:',row_means)
print()
normalized_matrix = random_matrix - row_means[:, np.newaxis]

print("Original Matrix:")
print(random_matrix)
print()
print("Matrix with row means subtracted:")
print(normalized_matrix)

Mean of each rows: [0.51108025 0.64141336 0.4211645 ]

Original Matrix:
[[0.07945305 0.98877767 0.08450956 0.89158074]
 [0.25174907 0.77680577 0.9558407  0.58125788]
 [0.23609981 0.87316508 0.06689923 0.50849387]]

Matrix with row means subtracted:
[[-0.43162721  0.47769742 -0.42657069  0.38050049]
 [-0.38966429  0.13539242  0.31442734 -0.06015547]
 [-0.18506469  0.45200058 -0.35426527  0.08732937]]


### 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [79]:
vector = np.array([1, 2, 3, 4, 5])

# Indices to add 1 to
indices_to_add = np.array([0, 1, 3, 4])

# Add 1 to the specified elements
vector[indices_to_add] += 1

print("Modified Vector:")
print(vector)

Modified Vector:
[2 3 3 5 6]


### 12.get the diagonal of a dot product

In [80]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


dot_product = np.dot(A, B)

diagonal = np.diag(dot_product) # Get the diagonal elements

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nDot Product:")
print(dot_product)

print("\nDiagonal of Dot Product:")
print(diagonal)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Dot Product:
[[19 22]
 [43 50]]

Diagonal of Dot Product:
[19 50]


### 13. find the most frequent value in an array

In [67]:
x = np.random.randint(0, 10, 50)

most_frequent_value = np.bincount(x).argmax()

print("Array:")
print(x,'\n')
print("Most frequent value:", most_frequent_value)

Array:
[6 2 3 9 1 6 9 8 8 3 8 8 6 0 8 2 8 7 8 2 0 5 8 8 7 5 9 5 7 7 9 8 6 9 1 8 7
 4 2 7 8 6 1 3 3 4 4 9 1 7] 

Most frequent value: 8


### 14. get the n largest values of an array

In [70]:
arr = np.array([45,2,-9,56,345,11,7,89,98])

n = int(input(f'Enter the n value between 1 and {len(arr)}:'))

n_largest_values = np.partition(arr, -n)[-n:]

print("Array:")
print(arr)
print(f"{n} Largest Values in Array :", n_largest_values)

Enter the n value between 1 and 9:4
Array:
[ 45   2  -9  56 345  11   7  89  98]
4 Largest Values in Array : [ 56  89  98 345]


### 15 .create a record array from a regular array

In [72]:
regular_array = np.array([("Selva", 22), ("Raj", 79)], dtype=[('name', 'U10'), ('age', int)])

record_array = np.rec.fromarrays(regular_array.T, names='name,age')

print("Regular Array:")
print(regular_array)
print()
print("Record Array:")
print(record_array)

Regular Array:
[('Selva', 22) ('Raj', 79)]

Record Array:
(('Selva', 22), ('Raj', 79))


### 16. swap two rows of an array

In [73]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Swapping rows 0 and 1
arr[[0, 1]] = arr[[1, 0]]

print("Array with Rows Swapped:")
print(arr)

Array with Rows Swapped:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


### 17. Write python code to reshape to the next dimension of numpy array?

In [76]:
x = np.array([[23, 34, 121],
              [23, 22, 67],
              [686, 434, 123]])


# Reshape to the next dimension (3x3x1)
reshaped_x = x.reshape((3, 3, 1))

print("Original Array (3x3):")
print(x)

print("\nReshaped Array (3x3x1):")
print(reshaped_x)

Original Array (3x3):
[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

Reshaped Array (3x3x1):
[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
